[package]
name = "pindorama"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = { version = "0.11", features = ["wayland"] }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
